# Configurações de conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/receitas_db
spring.datasource.username=postgres
spring.datasource.password=password123

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true